# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crapdb', '0002_auto_20171022_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flag',
        ),
    ]
