# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-19 16:50
from __future__ import unicode_literals

import core.util
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('display_name', models.CharField(default='', max_length=25, verbose_name='Display Name')),
                ('hacker_bucks', models.IntegerField(default=0, verbose_name='Hacker Bucks')),
                ('lifetime_hacker_bucks', models.IntegerField(default=0, verbose_name='Lifetime Hacker Bucks')),
                ('num_flags_found', models.IntegerField(default=0, verbose_name='Number of Flags Found')),
                ('claimed_flags', models.CharField(default='', max_length=4000, verbose_name='List of Claimed Flags')),
                ('playtime', models.CharField(max_length=25, verbose_name='Total Playtime')),
                ('percent_complete', models.IntegerField(default=0, verbose_name='Percent Complete')),
                ('secret_key', models.CharField(default='', max_length=128, verbose_name='Secret Key')),
                ('leader_oid', models.CharField(default=core.util.ObjectId, max_length=32, verbose_name='Leader OID')),
                ('session_creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Session Creation Time')),
                ('purchased_challenges', models.CharField(default='', max_length=4000, verbose_name='Purchased Challenges')),
                ('remote_ip', models.CharField(default='', max_length=64, verbose_name='Remote IP')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('leader_created', models.DateTimeField(auto_now_add=True, verbose_name='Leader Created Time')),
            ],
        ),
    ]
