# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('hacker_bucks', models.IntegerField(default=0, verbose_name='Hacker Bucks')),
                ('lifetime_hacker_bucks', models.IntegerField(default=0, verbose_name='Lifetime Hacker Bucks')),
                ('flags_found', models.IntegerField(default=0, verbose_name='Flags found')),
                ('playtime', models.CharField(max_length=25, verbose_name='Total Playtime')),
            ],
        ),
    ]
