# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='percent_complete',
            field=models.IntegerField(default=0, verbose_name='Percent Complete'),
        ),
    ]
