# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_leaderboardentry_percent_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboardentry',
            name='flags_found',
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='claimed_flags',
            field=models.CharField(default='', max_length=4000, verbose_name='List of Claimed Flags'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='leader_oid',
            field=models.CharField(default='a44216013eed4dcfb2e1e455e264198f', max_length=32, verbose_name='Leader OID'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='num_flags_found',
            field=models.IntegerField(default=0, verbose_name='Number of Flags Found'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='secret_key',
            field=models.CharField(default='', max_length=128, verbose_name='Secret Key'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='session_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 12, 49, 25, 541165), verbose_name='Session Creation Time'),
        ),
    ]
