# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_auto_20171202_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='leader_oid',
            field=models.CharField(default='3f8daf9d351b45a482ca217838234e67', max_length=32, verbose_name='Leader OID'),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='session_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 12, 50, 34, 946066, tzinfo=utc), verbose_name='Session Creation Time'),
        ),
    ]
