# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_auto_20171202_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='leader_oid',
            field=models.CharField(default='6764db92edb04e0ea69bb497ed12d7e5', max_length=32, verbose_name='Leader OID'),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='session_creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Session Creation Time'),
        ),
    ]
