# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_auto_20171202_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='leader_oid',
            field=models.CharField(default='081de04fc6824e7aa1dc4bcff87ee236', max_length=32, verbose_name='Leader OID'),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='session_creation_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Session Creation Time'),
        ),
    ]
