# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_auto_20171203_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='leader_oid',
            field=models.CharField(default='406be2bab1cb4dca998f5c912c993941', max_length=32, verbose_name='Leader OID'),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='session_creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Session Creation Time'),
        ),
    ]
