# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0009_auto_20171203_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='purchased_challenges',
            field=models.CharField(default='', max_length=4000, verbose_name='Purchased Challenges'),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='leader_oid',
            field=models.CharField(default='7d7c86f8b2c14cccbf498e049a845e72', max_length=32, verbose_name='Leader OID'),
        ),
    ]
