# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0010_auto_20171203_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='remote_ip',
            field=models.CharField(default='', max_length=64, verbose_name='Remote IP'),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='leader_oid',
            field=models.CharField(default='3206bad956144a47864985727b077648', max_length=32, verbose_name='Leader OID'),
        ),
    ]
