# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0011_auto_20171204_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='leader_oid',
            field=models.CharField(default='70bbf96e43e2418a84abc1b5166a2d77', max_length=32, verbose_name='Leader OID'),
        ),
    ]
