# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-19 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0012_auto_20171209_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='leader_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='leader_oid',
            field=models.CharField(default='653a6e0788fb4cb98854667c35d541f9', max_length=32, verbose_name='Leader OID'),
        ),
    ]
