# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-19 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=100, verbose_name='Flag')),
                ('value', models.IntegerField(default=0, verbose_name='Flag Value')),
            ],
        ),
    ]
